bag/urls.py
"""
MILESTONE PROJECT 4 by MIKHAILA BURGESS
Bag app URLs for "SERENITEA EMPORIUM"
- - - - - - - - - - - - - - - - - - - -
"""

# from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
]

products/urls.py
"""
Product app URLs for "SERENITEA EMPORIUM"
- - - - - - - - - - - - - - - - - - - -
"""

# from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
]

serenitea/urls.py
""" SereniTea URL Configuration

    Contains the `urlpatterns` list routes 
    URLs to all SereniTea app views. 
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
"""
Product Models for "SERENITEA EMPORIUM"
- - - - - - - - - - - - - - - - - - - -
"""
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    friendly_name = models.CharField(max_length=200, null=False,
                                     default="Product Category")
    name = models.CharField(max_length=200)
    group = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):

    class Meta:
        verbose_name_plural = 'Products'

    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    sku = models.CharField(max_length=10, null=True, blank=True)
    friendly_name = models.CharField(max_length=200, null=False,
                                     default="Store Product")
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    alt_text = models.TextField(null=True, blank=True)
    bs_icon = models.CharField(max_length=100, null=True, blank=True)
    weight = models.IntegerField(null=True, blank=True)
    organic = models.CharField(max_length=3, null=True, blank=True)
    strength = models.IntegerField(null=True, blank=True)
    brew_time = models.CharField(max_length=10, null=True, blank=True)
    water_temp = models.IntegerField(null=True, blank=True)
    price = models.DecimalField(max_digits=6, null=False, decimal_places=2)
    stock_level = models.IntegerField(null=True, blank=True)
    rating = models.DecimalField(max_digits=4, decimal_places=2, null=True, 
                                 blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name

    def get_summary(self):
        return (f'{self.friendly_name} [sku: {self.sku[0:6]}] @ £{self.price}')

products/forms.py
"""
Product forms for "SERENITEA EMPORIUM"
- - - - - - - - - - - - - - - - - - - -
"""
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False,
                             widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(category.id, category.get_friendly_name())
                          for category in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

products/views.py
"""
Product Views for "SERENITEA EMPORIUM"
- - - - - - - - - - - - - - - - - - - -
"""
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q  # to generate search queries in Django
from django.db.models.functions import Lower

from .models import Product, Category
from .forms import ProductForm


# Product app views

def all_products(request):
    """ View to show all products """
    products = Product.objects.all()  # retrieve all products from database
    # initialise initial view selectors to None (i.e. unspecified)
    categories = None
    group = None
    sort = None
    direction = None
    query = None

    if request.GET:
        # Handle user submitting a sort request
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'

            products = products.order_by(sortkey)

        # Handle user submitting search request
        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request,
                               ("You didn't enter any search criteria!"))
                return redirect(reverse('products'))

            # Filter if search term present in product name OR description
            queries = Q(name__icontains=query) | Q(description__icontains=query) | Q(alt_text__icontains=query)
            products = products.filter(queries)

        # Handle user submitting request to view products in specific category
        if 'category' in request.GET:
            # allow for multiple categories
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            # get category objects to enable access to category fields
            categories = Category.objects.filter(name__in=categories)

        # Handle user submitting request to view all products in group
        if 'group' in request.GET:
            group = request.GET['group']
            # obtain all categories where Category.group = requested group
            categories = Category.objects.filter(group__iexact=group)
            # iterate through the group categories to extract list of names
            names = []
            for category in categories:
                names.append(category.name)
            # filter products based on category name
            products = products.filter(category__name__in=names)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'current_sorting': current_sorting,
        'current_group': group,
        'current_categories': categories,
        'search_term': query,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ View to show details of individual products """

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'products/product_detail.html', context)


@login_required(login_url="/accounts/login/")
def add_product(request):
    """ Add a new product to the store """
    # Check user has permission to access this feature
    if not request.user.is_superuser:
        messages.error(request,
                       'Oops! You are not authorized to access that page.')
        return redirect(reverse('home'))

    # Handle POST requests
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'New product successfully added \
                             to store catalogue.')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product. Please check \
                           the form is valid.')
    else:
        # Handle GET requests
        form = ProductForm()
        template = 'products/add_product.html'
        context = {
            'form': form,
        }

    return render(request, template, context)


@login_required(login_url="/accounts/login/")
def edit_product(request, product_id):
    """ Update details of an existing store product """
    # Check user has permission to access this feature
    if not request.user.is_superuser:
        messages.error(request, 'Oops! You are not authorized to \
                       access that page.')
        return redirect(reverse('home'))

    # retrieve details of the selected product
    product = get_object_or_404(Product, pk=product_id)
    # Handle POST requests
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product successfully updated in \
                             store catalogue.')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to update product. Please \
                           ensure the form is valid.')
    else:
        # Handle GET requests
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.friendly_name}')
        template = 'products/edit_product.html'
        context = {
            'form': form,
            'product': product,
        }

    return render(request, template, context)


@login_required(login_url="/accounts/login/")
def delete_product(request, product_id):
    """ Delete a product from the store catalogue """
    # Check user has permission to access this feature
    if not request.user.is_superuser:
        messages.error(request,
                       'Oops! You are not authorized to access that page.')
        return redirect(reverse('home'))

    # retrieve details of the selected product
    product = get_object_or_404(Product, pk=product_id)
    # Delete product from database
    product.delete()
    messages.success(request, 'Product successfully deleted.')
    return redirect(reverse('products'))

products/templates/products/add_product.html
<!-- 
    MILESTONE PROJECT 4 by MIKHAILA BURGESS
    "SERENITEA EMPORIUM"
    - - - - - - - - - - - - - - - - - - - -
-->

{% extends 'base.html' %}
{% load static %}

{% block extra_title %}
- Add a New Product
{% endblock %}

{% block content %}
<!-- Page Title -->
<div id="page-title" class="row">
    <div class="col-12 my-auto">
        <hr class="title-border">
        <h2 class="page-title-font my-0">Add a Product</h2>
        <hr class="title-border">
    </div>
</div>

<!-- Add Product Form -->
<div class="add-product-page container">
    <div class="row mx-auto">
        <!-- Product Details -->
        <div class="col-10 offset-1 my-auto">
            <p class="lead mb-2">Complete the following form to add a new product to the store</p>
            <form action="{% url 'add_product' %}" method="POST" id="new-product-form" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'image' %}
                        {{ field | as_crispy_field }}
                    {% else %}
                        {{ field }}
                    {% endif %}
                {% endfor %}

                <!-- Product Submit button -->
                <div class="submit-button text-right mt-5 mb-2">
                    <!-- Cancel and link back to products -->
                    <a href="{% url 'products' %}" class="site-btn btn">
                        <span class="icon">
                            <i class="bi bi-arrow-left-circle"></i>
                        </span>
                        <span class="font-weight-bold">Cancel</span>
                    </a>
                    <!-- Save new product details -->
                    <button id="submit-button" class="site-btn btn">
                        <span class="font-weight-bold">Add Product</span>
                        <span class="icon">
                            <i class="bi bi-plus-circle-fill"></i>
                        </span>
                    </button>
                </div>
            </form>
            <p></p>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        // When new image selected, display name to user
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Product image will be set to: ${file.name}`);
        });

        // When product friendly name entered, automatically generate system name 
        $('#id_friendly_name').change(function(e) {
            $('#id_name').attr("value", 
            $('#id_friendly_name').val().replaceAll(" ", "_").replaceAll("'", "").replaceAll('"', "").toLowerCase());
        });
    </script>
{% endblock %}

products/templates/products/edit_product.html
<!-- 
    MILESTONE PROJECT 4 by MIKHAILA BURGESS
    "SERENITEA EMPORIUM"
    - - - - - - - - - - - - - - - - - - - -
-->

{% extends 'base.html' %}
{% load static %}

{% block extra_title %}
- Edit Product
{% endblock %}

{% block content %}
<!-- Page Title -->
<div id="page-title" class="row">
    <div class="col-12 my-auto">
        <hr class="title-border">
        <h2 class="page-title-font my-0">Edit Existing Product</h2>
        <hr class="title-border">
    </div>
</div>

<!-- Add Product Form -->
<div class="add-product-page container">
    <div class="row mx-auto">
        <!-- Product Details -->
        <div class="col-10 offset-1 my-auto">
            <p class="lead mb-2">Use the following form to update product details</p>
            <form action="{% url 'edit_product' product.id %}" method="POST" id="edit-product-form" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'image' %}
                        {{ field | as_crispy_field }}
                    {% else %}
                        {{ field }}
                    {% endif %}
                {% endfor %}

                <!-- Product Submit button -->
                <div class="submit-button text-right mt-5 mb-2">
                    <!-- Cancel and link back to products -->
                    <a href="{% url 'product_detail' product.id %}" class="site-btn btn">
                        <span class="icon">
                            <i class="bi bi-arrow-left-circle"></i>
                        </span>
                        <span class="font-weight-bold">Cancel</span>
                    </a>
                    <!-- Save new product details -->
                    <button id="submit-button" class="site-btn btn">
                        <span class="font-weight-bold">Update Product</span>
                        <span class="icon">
                            <i class="bi bi-pencil-square"></i>
                        </span>
                    </button>
                </div>
            </form>
            <p></p>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        // When new image selected, display name to user
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Product image will be set to: ${file.name}`);
        });

        // When product friendly name entered, automatically generate system name 
        $('#id_friendly_name').change(function(e) {
            $('#id_name').attr("value", 
            $('#id_friendly_name').val().replaceAll(" ", "_").replaceAll("'", "").replaceAll('"', "").toLowerCase());
        });
    </script>
{% endblock %}

products/templates/products/product_detail.html
<!-- 
    MILESTONE PROJECT 4 by MIKHAILA BURGESS
    "SERENITEA EMPORIUM"
    - - - - - - - - - - - - - - - - - - - -
-->

{% extends 'base.html' %}
{% load static %}

{% block extra_title %}
- {{ product.friendly_name }}
{% endblock %}

{% block extra_meta %}
<meta name="description" content="SereniTea Emporium - {{ product.friendly_name }} : {{ product.description }}">
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">

        <!-- Product Image -->
        <div class="col-10 offset-1 col-md-5 offset-md-1">
            <div class="image-container my-5 text-center">
                {% if product.image %}
                <a href="{% static 'media/' %}{{ product.image }}" target="_blank">
                    <img id="product-img" class="card-img-top img-fluid product-img"
                        src="{% static 'media/' %}{{ product.image }}" alt="{{ product.name }}">
                </a>
                {% else %}
                <a href="{% static 'media/noimage.png' %}" target="_blank">
                    <img class="card-img-top img-fluid product-img" src="{% static 'media/noimage.png' %}"
                        alt="No image available for {{ product.friendly_name }}">
                </a>
                {% endif %}
            </div>
        </div>

        <!-- Product Overview -->
        <div class="col-10 offset-1 col-md-6 offset-md-0">
            <div class="product-details-container mb-3 mb-lg-5 mt-2 mt-md-5">
                <h2 class="mb-0 product-name">{{ product.friendly_name }}</h2>
                {% if product.category %}
                <a class="product-category-label" href="{% url 'products' %}?category={{ product.category.name }}">{{ product.category.friendly_name }}</a>
                {% else %}
                <a class="product-category-label" href="{% url 'products' %}">SereniTea Product Catalogue</a>
                {% endif %}
                <p class="lead mb-0 text-left font-weight-bold">£{{ product.price }} {% if product.weight %}<small> ({{ product.weight }}g) </small>{% endif %}</p>
                {% if product.rating %}
                <small class="text-muted"><i class="bi bi-star-fill"></i>{{ product.rating }} / 5</small>
                {% else %}
                <small class="text-muted">No Rating</small>
                {% endif %}

                {% if request.user.is_superuser %}
                <p>
                    <a class="edit-option text-success" href="{% url 'edit_product' product.id %}">
                        <small>Edit <i class="bi bi-pencil-square"></i></small></a>
                    &ensp;
                    <a class="delete-option text-danger" href="{% url 'delete_product' product.id %}">
                        <small>Delete <i class="bi bi-trash"></i></small></a>
                    &emsp;
                    <small class="border border-dark rounded px-1">Stock level:
                        {% if product.stock_level > 0 %}
                        {{ product.stock_level }}
                        {% elif product.stock_level == 0 %}
                        <em>sold out</em>
                        {% else %}
                        N/A
                        {% endif %}
                    </small>
                </p>
                {% endif %}
            </div>

            <!-- Form to add items to basket -->
            <form class="form" action="{% url 'add_to_basket' product.id %}" method="POST">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-12">
                        <p class="mt-2"><strong>Quantity:</strong></p>
                        <div class="form-group mt-2 w-50 d-flex flex-md-row">
                            <div class="input-group">
                                {% if product.stock_level == 0 %}
                                <input class="form-control qty_input" type="number" name="quantity" value="0" disabled>
                                {% else %}
                                <input class="form-control qty_input" type="number" name="quantity" value="1" min="1"
                                    max="99" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}">
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <div class="col-12 d-flex flex-column-reverse flex-md-row gap-1">
                        <a href="{% url 'products' %}" class="site-btn btn mt-2">
                            <span class="icon">
                                <i class="bi bi-arrow-left-circle"></i>
                            </span>
                            <span>Keep Shopping</span>
                        </a>
                        {% if product.stock_level == 0 %}
                        <input type="submit" class="site-btn btn mt-2 text-danger" value="Out of Stock" disabled>
                        {% else %}
                        <input type="submit" class="site-btn btn mt-2" value="Add to Basket">
                        {% endif %}
                    </div>
                    <!-- pass URL to enable redirect from basket -->
                    <input type="hidden" name="redirect_url" value="{{ request.path }}">
                </div>
            </form>
        </div>
    </div>

    <!-- Product Description -->
    <div class="row">
        <div class="col-10 offset-1">
            <div class="product-description-container">
                {% if product.description %}
                {{ product.description|safe }}
                {% else %}
                <p><em>Product description coming soon ...</em></p>
                {% endif %}

                <!-- Additional Product Details - specifically for Teas -->
                <div class="text-center">
                    {% if product.organic %}
                    <span class="d-inline p-2">
                        <small>
                            {% if product.organic == 'yes' %}
                            <i class="bi bi-check2-circle"> <strong>Organic</strong></i>
                            {% elif product.organic == 'no' %}
                            <i class="bi bi-x-circle-fill"></i> <strong>Non-organic</strong>
                            {% endif %}
                        </small>
                    </span>
                    {% endif %}

                    {% if product.brew_time %}
                    <span class="d-inline p-2"><small><i class="bi bi-cup-hot-fill"></i>
                            <strong> Brew Time (mins) -</strong> {{ product.brew_time }}</small>
                    </span>
                    {% endif %}

                    {% if product.water_temp %}
                    <span class="d-inline p-2" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true"
                        data-bs-title="Boiling (100) <i class='bi bi-thermometer-high'></i><br>
                                Hot (over 80) <i class='bi bi-thermometer-half'></i><br>
                                Low (over 60) <i class='bi bi-thermometer-low'></i><br>
                                Cold <i class='bi bi-thermometer'></i>">
                        <small>
                            {% if product.water_temp == 100 %} <i class="bi bi-thermometer-high"></i>
                            {% elif product.water_temp > 80 %} <i class="bi bi-thermometer-half"></i>
                            {% elif product.water_temp > 60 %} <i class="bi bi-thermometer-low"></i>
                            {% else %} <i class="bi bi-thermometer"></i>
                            {% endif %}
                            <strong>Brew Temperature -</strong> {{ product.water_temp}}&#8451;
                        </small>
                    </span>
                    {% endif %}

                    {% if product.strength %}
                    <span class="d-inline p-2" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true"
                        data-bs-title="Mild (1-2) <i class='bi bi-droplet'></i><br>
                                Medium (3) <i class='bi bi-droplet-half'></i><br>
                                Strong (4-5) <i class='bi bi-droplet-fill'></i>">
                        <small>
                            {% if product.strength == 1 %} <i class="bi bi-droplet"></i>
                            {% elif product.strength == 2 %} <i class="bi bi-droplet"></i>
                            {% elif product.strength == 3 %} <i class="bi bi-droplet-half"></i>
                            {% elif product.strength == 4 %} <i class="bi bi-droplet-fill"></i>
                            {% elif product.strength == 5 %} <i class="bi bi-droplet-fill"></i>
                            {% endif %}
                            <strong>Strength -</strong> {{ product.strength}}
                        </small>
                    </span>
                    {% endif %}
                </div>
                {% if request.user.is_authenticated %}
                <br>
                <hr class="title-border">
                <p class="text-center fw-lighter review-link-text">Have you tried this product? Let us know what you thought by completing our
                    <a class="review-link fw-light" href="{% url 'review_product' product.id %}">product review form.</a>
                </p>
                {% endif %}
            </div>
        </div>
    </div>

    {{ block.super }}
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script>
    // enable page tooltips
    $(document).ready(function () {
        $('[data-bs-toggle="tooltip"]').tooltip();
    });

    // If unable to load product image, display 'noimage.png' instead
    $('#product-img').on("error", function () {
        $('#product-img').attr('src', '{% static "media/noimage.png" %}')
    })      
</script>
{% endblock %}